### ISSUE TITLE
TypeError: Cannot read property 'rpc' of undefined

### ISSUE THREAD

**Issue by jtremback** [forbole/big_dipper#102]
Having followed the instructions to build and deploy the app (and installing mongodb, which was not in the instructions), I am getting the following error when trying to start the application.

root@althea-validator:~/bundle# MONGO_URL='mongodb://127.0.0.1:27017/meteor' ROOT_URL='http://159.65.74.76'  node main.js
/root/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'rpc' of undefined
    at main.js (server/main.js:10:30)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /root/bundle/programs/server/app/app.js:3984:1
    at /root/bundle/programs/server/boot.js:419:36
    at Array.forEach (<anonymous>)
    at /root/bundle/programs/server/boot.js:228:19
    at /root/bundle/programs/server/boot.js:479:5
    at Function.run (/root/bundle/programs/server/profile.js:510:12)
    at /root/bundle/programs/server/boot.js:478:11

**Comment by jtremback** [comment]
This is with the bundle generated by build.sh

**Comment by kwunyeung** [comment]
Thank you for opening the issue. Clearly we need better documentation on this. Many settings are set in the `settings.json` which can be included if you run with `meteor --settings settings.json`. When you run built Meteor package, you have to setup the environment variables as it won't take your settings.json file in order to run it correctly. Please take a look at the docs of  [METEOR_SETTINGS](https://docs.meteor.com/environment-variables.html#METEOR-SETTINGS) and [deployment](https://guide.meteor.com/deployment.html#custom-deployment).
